FROM alpine:3.18

WORKDIR /app

RUN apk add --no-cache git make gcc musl-dev

RUN git clone https://github.com/catseye/Befunge-93.git /tmp/befunge && \
    cd /tmp/befunge && make && cp bin/bef /usr/local/bin/bef && \
    rm -rf /tmp/befunge