FROM debian:bullseye-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/catseye/Befunge-93.git /app/Befunge-93

WORKDIR /app/Befunge-93

RUN make

WORKDIR /app

RUN cp Befunge-93/bin/bef /app/bef && rm -rf Befunge-93

COPY app/main.bf ./main.bf

CMD ["/app/bef", "/app/main.bf"]