jenkins:
  systemMessage: "Welcome to the Whanos Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "http://localhost/jenkins/"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - file: /usr/share/jenkins/ref/jobs/build_base_image.groovy
  - file: /usr/share/jenkins/ref/jobs/link_project.groovy
